apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- ns.yaml                 # Namespaces
#- srv-acct.yaml           # ServiceAccounts
#- cr/crd/crd.yaml         # Custom Resource Definitions (CRDs) - MUST come before CRs
#- cr/crd/role/role.yaml   # Roles
#- cr/crd/role/bind.yaml   # RoleBindings
- cfm.yaml                 # ConfigMaps
- scrt.yaml                # Secrets (place before dpl/pod that use them)
#- pv.yaml                 # Persistent Volume
- pvc.yaml                # Persistent Volume Claim
- dpl.yaml                 # Deployments
#- dpl-load.yaml             # Deployments
- svc.yaml                 # Services
#- pod.yaml                # Temporary Pods
#- pod-test.yaml            # Test Pods
#- cr/cr.yaml              # Custom Resources (CRs)
- hpa.yaml                 # HorizontalPodAutoscalers
- crj.yaml                  # CronJob to test