apiVersion: v1
kind: Service
metadata:
  name: quakewatch-web-svc
spec:
  selector:
    app: quakewatch-web
  ports:
    - protocol: TCP
      port: 5011        # Service port (for clients inside the cluster)
      targetPort: 5000  # Port your container is listening on
  type: LoadBalancer # Exposes the service on Node's Port