apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quake-watch-app-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/alkon
    targetRevision: 0.1.0
    chart: quake-watch-app-chart
    helm:
      values: |
        image:
          tag: latest
        replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
