apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quake-watch-app-chart-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/alkon # Base OCI registry URL
    targetRevision: 0.3.0
    chart: quake-watch-app-chart
    helm:
      values: |
        replicaCount: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
