name: Deploy the Python App & Helm Chart

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy: # Corrected job definition starts here
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Removed: Download Chart Version Artifact step

      - name: Set up Kubeconfig for K3D Cluster
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Get ArgoCD Admin Password
        id: get_argocd_password
        run: |
          ARGO_CD_INITIAL_PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
          echo "Retrieved ArgoCD Admin Password."
          echo "argocd_password=$ARGO_CD_INITIAL_PASSWORD" >> "$GITHUB_OUTPUT"

      - name: Log in to ArgoCD
        run: |
          argocd login ${{ secrets.ARGO_CD_SERVER }} \
            --username admin \
            --password ${{ steps.get_argocd_password.outputs.argocd_password }} \
            --insecure

      - name: Trigger ArgoCD Application Sync
        run: |
          APP_NAME="quake-watch-app-gitops" # Directly use the application name

          echo "Setting ArgoCD application target revision to main: ${APP_NAME}"
          # Temporarily set the targetRevision of the ArgoCD application to 'main'
          # This is the workaround to allow syncing to HEAD when the app is configured to a specific version.
          argocd app set "$APP_NAME" --revision main

          echo "Triggering sync for ArgoCD application: ${APP_NAME}"
          argocd app sync "$APP_NAME" --revision HEAD --prune 

